apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: monitoring
  labels:
    k8s-app: alertmanager
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 1m
      slack_api_url: 'https://hooks.slack.com/services/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'
    receivers:
    - name: 'slack-notificaions'
      slack_configs:
      - channel: '#prometheus-alerts'
        send_resolved: true
    route:
      group_interval: 5m
      group_wait: 10s
      receiver: 'slack-notificaions'
      repeat_interval: 3h