version: "3.9"

services:
  flask-app:
    build: .
    image: cloudhw3-flask
    ports:
      - "5000:5000"
    environment:
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - FLASK_ENV=development
    depends_on:
      - mongodb

  mongodb:
    image: mongo:4.4
    container_name: "mongodb"
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongodb_data:
