apiVersion: v1
kind: ReplicationController
metadata:
  name: flaskapp-rc
spec:
  replicas: 3
  selector:
    app: flaskapp
  template:
    metadata:
      labels:
        app: flaskapp
    spec:
      containers:
      - name: flaskapp
        image: jw4202/cloudhw3:health-route
        env:
        - name: MONGO_HOST
          value: "mongodb"
        - name: MONGO_PORT
          value: "27017"
        - name: FLASK_ENV
          value: "production"
        ports:
        - containerPort: 5000
